"""
Email sending via Gmail SMTP.
Uses STARTTLS on port 587.
"""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def send_email(to: str, subject: str, body: str) -> None:
    """
    Send an email via Gmail SMTP.

    Args:
        to: Recipient email address
        subject: Email subject line
        body: Email body (plain text — will be sent as HTML-wrapped text)
    """
    gmail_address = os.environ.get("GMAIL_ADDRESS", "")
    gmail_app_password = os.environ.get("GMAIL_APP_PASSWORD", "")

    if not gmail_address or not gmail_app_password:
        raise ValueError("GMAIL_ADDRESS and GMAIL_APP_PASSWORD must be set")

    msg = MIMEMultipart("alternative")
    msg["From"] = gmail_address
    msg["To"] = to
    msg["Subject"] = subject

    # Convert plain text to basic HTML for nice rendering
    html_body = _text_to_html(body)
    msg.attach(MIMEText(body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(gmail_address, gmail_app_password)
        server.send_message(msg)


def _text_to_html(text: str) -> str:
    """Convert LLM-generated text (possibly markdown) to basic HTML."""
    import re

    # Escape HTML entities
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    # Convert markdown-style headers
    text = re.sub(r"^### (.+)$", r"<h3 style='color:#4f46e5;margin:16px 0 8px;'>\1</h3>", text, flags=re.MULTILINE)
    text = re.sub(r"^## (.+)$", r"<h2 style='color:#4f46e5;margin:20px 0 8px;'>\1</h2>", text, flags=re.MULTILINE)
    text = re.sub(r"^# (.+)$", r"<h1 style='color:#4f46e5;margin:24px 0 12px;'>\1</h1>", text, flags=re.MULTILINE)

    # Bold and italic
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)

    # Convert newlines to <br>
    text = text.replace("\n", "<br>\n")

    return f"""
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                max-width: 600px; margin: 0 auto; padding: 24px;
                color: #1e293b; line-height: 1.6;">
        {text}
        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 32px 0 16px;">
        <p style="color: #94a3b8; font-size: 12px;">
            Generated by CronAI — AI-powered task scheduler
        </p>
    </div>
    """
